# Generated by Django 5.2 on 2025-07-02 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experts_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Experts')),
                ('subject_image', models.ImageField(upload_to='experts')),
                ('experts_department',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Experts')),
            ],
        ),
    ]
