# Generated by Django 5.2 on 2025-07-09 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_experts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experts',
            options={'verbose_name_plural': 'Experts'},
        ),
        migrations.RemoveField(
            model_name='experts',
            name='experts_name',
        ),
        migrations.AddField(
            model_name='experts',
            name='experts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experts_class', to='home.classes'),
        ),
        migrations.AlterField(
            model_name='experts',
            name='experts_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experts_department_class', to='home.classes'),
        ),
    ]
