# Generated by Django 5.2 on 2025-07-09 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_experts_options_remove_experts_experts_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experts',
            name='experts',
        ),
        migrations.AddField(
            model_name='experts',
            name='experts_name',
            field=models.CharField(default='Default Expert', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experts',
            name='experts_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experts_department_class', to='home.classes'),
        ),
    ]
