# Generated by Django 5.2 on 2025-07-09 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_experts_experts_experts_experts_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experts',
            name='experts_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.classes'),
        ),
    ]
