# Generated by Django 5.1.2 on 2025-07-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_experts_experts_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experts',
            options={},
        ),
        migrations.RemoveField(
            model_name='experts',
            name='experts_department',
        ),
        migrations.RemoveField(
            model_name='experts',
            name='experts_name',
        ),
        migrations.RemoveField(
            model_name='experts',
            name='subject_image',
        ),
        migrations.AddField(
            model_name='experts',
            name='description',
            field=models.TextField(default='No description provided'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='experts/'),
        ),
        migrations.AddField(
            model_name='experts',
            name='name',
            field=models.CharField(default='Unknown Expert', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experts',
            name='specialization',
            field=models.CharField(default='General Ayurveda', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classes',
            name='classes_name',
            field=models.CharField(max_length=200),
        ),
    ]
